version: 2
updates:
  # configuration for the root directory
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # configuration for the 1wire directory
  - package-ecosystem: "docker"
    directory: "/1wire"
    schedule:
      interval: "monthly"

  # configuration for the device directory
  - package-ecosystem: "docker"
    directory: "/device"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/device/.devcontainer"
    schedule:
          interval: "monthly"

  # configurations for the python files in the device directory
  - package-ecosystem: "pip"
    directory: "/device"
    schedule:
      interval: "monthly"
    # group the dependencies into a single PR
    groups:
      # Name for the group of dependencies
      python-updates:
        update-types:
          - "major"
          - "minor"
          - "patch"
