version: '3.8'

services: 
    device:
        image: nstoik/fd_device:dev
        build:
            target: dev-stage

    database_management:
        image: nstoik/fd_device:dev
        build:
            target: dev-stage

    1wire:
        image: nstoik/fd_1wire:dev
        labels:
            - "traefik.http.routers.fd_1wire.rule=PathPrefix(`/`)"
            - "traefik.http.routers.fd_1wire.entrypoints=web"

    traefik:
        ports:
            - $TRAEFIK_ACCESS_PORT:80
            # - 443:443
            # The Web UI (enabled by --api.insecure=true)
            - "$TRAEFIK_WEBUI_PORT:8080"
        volumes:
            - ./traefik/traefik.dev.yml:/etc/traefik/traefik.yml

    pgadmin:
        labels:
            - "traefik.http.routers.fd_pgadmin.rule=PathPrefix(`/pgadmin`)"
            - "traefik.http.routers.fd_pgadmin.entrypoints=web"

