version: '3.8'

services: 
    device:
        image: nstoik/fd_device:${FD_DEVICE}
        container_name: fd_device
        build:
            context: ./device
            dockerfile: Dockerfile
        environment:
            FD_DEVICE_CONFIG: ${FD_DEVICE_CONFIG}
            RABBITMQ_HOST_ADDRESS: ${RABBITMQ_HOST_ADDRESS}
        networks:
            - farm_device
        depends_on:
            - "database"
            - "1wire"
            - "database_management"
        volumes:
            - "logs:/logs"
            - "/sys/devices/w1_bus_master1:/sys/devices/w1_bus_master1"
        restart: on-failure

    database_management:
        image: nstoik/fd_device:${FD_DEVICE}
        container_name: fd_database_management
        command: ["pipenv", "run", "fd_device", "database", "database_upgrade", "--revision", "head"]
        build:
            context: ./device
            dockerfile: Dockerfile
        environment:
            FD_DEVICE_CONFIG: ${FD_DEVICE_CONFIG}
        networks:
            - farm_device
        depends_on:
            - "database"

    1wire:
        image: nstoik/fd_1wire:${FD_1WIRE}
        container_name: fd_1wire
        build:
            context: ./1wire
            dockerfile: Dockerfile
        devices:
            - "/dev/i2c-1:/dev/i2c-1"
        networks:
            - farm_device
        restart: unless-stopped
        labels:
            - custom.label=farm_device
            - traefik.enable=true
            - traefik.http.services.fd_1wire.loadbalancer.server.port=${FD_1WIRE_PORT}
            - traefik.http.routers.fd_1wire.service=fd_1wire
            # this middleware strips the prefix from the request path
            - traefik.http.middlewares.fd_1wire_strip_prefix.stripprefix.prefixes=/1wire
            - traefik.http.routers.fd_1wire.middlewares=fd_1wire_strip_prefix@docker


    # traefik container configuration below
    traefik:
        image: traefik:latest
        container_name: fd_traefik
        networks:
            - farm_device
        # ports are set in the docker-compose.dev and docker-compose.prod files
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - traefik:/letsencrypt
        environment:
            - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
            - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
        restart: unless-stopped
        depends_on:
            - device
            - 1wire
        labels:
        -  custom.label=farm_device

    # standard docker containers below

    database:
        image: postgres:14
        container_name: fd_database
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - "dbdata:/var/lib/postgresql/data"
        networks:
            - farm_device
        labels:
            - custom.label=farm_device

    pgadmin:
        container_name: fd_pgadmin
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
            SCRIPT_NAME: /pgadmin
        depends_on:
            - "database"
        volumes:
            - pgadmin:/root/.pgadmin
            - pgadmin:/var/lib/pgadmin
            - ./pgadmin/server_definition.json:/pgadmin4/servers.json:ro
        networks:
            - farm_device
        restart: unless-stopped
        labels:
            - custom.label=farm_device
            - traefik.enable=true
            - traefik.http.services.fd_pgadmin.loadbalancer.server.port=80
            - traefik.http.routers.fd_pgadmin.service=fd_pgadmin
  
volumes:
    logs:
    dbdata:
    pgadmin:
    traefik:

networks:
    farm_device:
        name: farm_device