version: '3.8'

services: 
    device:
        image: nstoik/farm_device_device:dev
        container_name: device
        build:
            context: ./device
            dockerfile: .devcontainer/dev.Dockerfile
        volumes:
            # this is for vs code file editing inside the container
            - .:/workspaces:cached
            # this is for bash command history. https://code.visualstudio.com/docs/remote/containers-advanced#_persist-bash-history-between-runs
            - bashhistory:/commandhistory
        # Overrides default command so things don't shut down after the process ends.
        command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
    bashhistory: