version: '3.8'

services: 
    device:
        image: nstoik/fd_device:dev
        build:
            target: dev-stage

    1wire:
        image: nstoik/fd_1wire:dev

    traefik:
        ports:
            - 80:80
            # - 443:443
            # The Web UI (enabled by --api.insecure=true)
            - "8080:8080"
        volumes:
            - ./traefik/traefik.dev.yml:/etc/traefik/traefik.yml
