version: '3.8'

services:
    device:
        build:
            target: prod-stage

    database_management:
        build:
            target: prod-stage

    1wire:
        labels:
            - traefik.http.routers.fd_1wire.rule=Host(`${TRAEFIK_DOMAIN}`) && PathPrefix(`/`)
            - traefik.http.routers.fd_1wire.entrypoints=websecure
            - traefik.http.routers.fd_1wire.tls.certresolver=letsencrypt

    traefik:
        ports:
            - $TRAEFIK_ACCESS_PORT:80
            - $TRAEFIK_ACCESS_PORT_SECURE:443
        volumes:
            - ./traefik/traefik.prod.yml:/etc/traefik/traefik.yml
        labels:
            - traefik.enable=true
            - traefik.http.routers.fd_traefik.rule=Host(`traefik.${TRAEFIK_DOMAIN}`)
            - traefik.http.routers.fd_traefik.entrypoints=websecure
            - traefik.http.routers.fd_traefik.tls.certresolver=letsencrypt
            - traefik.http.routers.fd_traefik.service=api@internal

    pgadmin:
        labels:
            - traefik.http.routers.fd_pgadmin.rule=Host(`${TRAEFIK_DOMAIN}`) && PathPrefix(`/pgadmin`)
            - traefik.http.routers.fd_pgadmin.entrypoints=websecure
            - traefik.http.routers.fd_pgadmin.tls.certresolver=letsencrypt
