version: '3.8'

services: 
  fd_device:
    image: nstoik/fd_device:latest
    container_name: fd_device
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - farm_device
    depends_on:
      - "fd_db"
    volumes:
      - "logs:/logs"
    restart: unless-stopped
  fd_db:
    image: postgres:11
    container_name: "fd_db"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: farm_device
      POSTGRES_USER: fd
      POSTGRES_DB: farm_device.db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    networks:
      - farm_device
  fd_pgadmin:
    container_name: fd_pgadmin
    # the tag 'snapshot' is needed for running on arm64 hardware
    # image: dpage/pgadmin4:snapshot
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: fd@farmmonitor.ca
      PGADMIN_DEFAULT_PASSWORD: farm_device
    volumes:
        - pgadmin:/root/.pgadmin
        - pgadmin:/var/lib/pgadmin
    ports:
      - "5052:80"
    networks:
      - farm_device
    restart: unless-stopped
  
volumes:
  logs:
  dbdata:
  pgadmin:

networks:
  farm_device:
    name: farm_device