"""add string representation for grainbin bus

Revision ID: 1637cff09270
Revises: 45fd9deaf616
Create Date: 2021-10-18 05:52:52.460435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1637cff09270'
down_revision = '45fd9deaf616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grainbin', sa.Column('bus_number_string', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grainbin', 'bus_number_string')
    # ### end Alembic commands ###
