"""Update to sqlalchemy 2.0

Revision ID: 4988ca3aa994
Revises: 1637cff09270
Create Date: 2024-01-06 06:31:47.498478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4988ca3aa994'
down_revision = '1637cff09270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connection', 'first_connected',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('connection', 'is_connected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('device', 'device_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('device', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('device', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('device', 'grainbin_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('grainbin', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('grainbin', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('grainbin', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('grainbin', 'average_temp',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    op.alter_column('system_hardware', 'grainbin_reader_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('system_interface', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('system_interface', 'is_for_fm',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('system_interface', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('system_setup', 'first_setup',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('system_setup', 'first_setup_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('system_setup', 'standalone_configuration',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('system_wifi', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('system_wifi', 'password',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('system_wifi', 'mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_wifi', 'mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('system_wifi', 'password',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('system_wifi', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('system_setup', 'standalone_configuration',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('system_setup', 'first_setup_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('system_setup', 'first_setup',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('system_interface', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('system_interface', 'is_for_fm',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('system_interface', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('system_hardware', 'grainbin_reader_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grainbin', 'average_temp',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    op.alter_column('grainbin', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('grainbin', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('grainbin', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('device', 'grainbin_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('device', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('device', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('device', 'device_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('connection', 'is_connected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('connection', 'first_connected',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
