name: Device Build Status

on:
    push:
        paths:
            - 'device/**'

jobs:
  device-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: device/
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      - run: cp .env.example .env
      - name: Run Python lints
        run: pipenv run fd_device lint --check
      - name: Run Python tests
        run: pipenv run fd_device test --coverage
      #- name: Run Python docstrings
      #  run: pipenv run fd_device docstring
